"""Stage 2: Multi-LLM Ideation & Rotation Tests (test_multi_generation.py).

Verifies:
1. Round-robin model rotation across Gemini, Claude, and ChatGPT.
2. Specialized thematic dispatch to target frontier models.
3. Multi-model RFC proposal generation and persistence.
"""
from pathlib import Path
import pytest

from src.core.schema import ModelName, StrategyTarget, ProposalStatus
from src.core.proposal_manager import ProposalManager
from src.core.ideation import ContextBuilder, PromptBuilder


def test_multi_model_rotation():
    """Verify round-robin rotation order: Gemini -> Claude -> ChatGPT -> Gemini."""
    current = ModelName.GEMINI
    next_1 = PromptBuilder.get_next_model_in_rotation(current)
    assert next_1 == ModelName.CLAUDE

    next_2 = PromptBuilder.get_next_model_in_rotation(next_1)
    assert next_2 == ModelName.CHATGPT

    next_3 = PromptBuilder.get_next_model_in_rotation(next_2)
    assert next_3 == ModelName.GEMINI


def test_specialized_thematic_dispatch():
    """Verify routing research themes to specialized frontier models."""
    # Lookahead / causality / math audit -> Claude
    assert PromptBuilder.get_thematic_assignment("lookahead bias audit") == ModelName.CLAUDE
    assert PromptBuilder.get_thematic_assignment("mathematical causality verification") == ModelName.CLAUDE

    # Feature engineering / signal alpha / vol estimators -> Gemini
    assert PromptBuilder.get_thematic_assignment("intraday volatility indicator") == ModelName.GEMINI
    assert PromptBuilder.get_thematic_assignment("volume feature engineering") == ModelName.GEMINI

    # Hypothesis synthesis / regime analysis / general -> ChatGPT
    assert PromptBuilder.get_thematic_assignment("regime transition hypothesis") == ModelName.CHATGPT
    assert PromptBuilder.get_thematic_assignment("cross-model ensemble synthesis") == ModelName.CHATGPT


def test_multi_model_rfc_generation_and_persistence(tmp_path):
    """Verify all 3 frontier models can generate and persist valid RFCs with their specific branches."""
    pm = ProposalManager(base_dir=tmp_path / "proposals")

    models_branches = [
        (ModelName.GEMINI, "dev"),
        (ModelName.CLAUDE, "claude"),
        (ModelName.CHATGPT, "chatgpt"),
    ]

    for model, branch in models_branches:
        proposal = pm.create_proposal(
            title=f"Optimization by {model.value.title()}",
            author_model=model,
            target_strategy=StrategyTarget.STANDALONE_TB,
            assigned_branch=branch,
            hypothesis=f"Hypothesis generated by {model.value}",
            proposed_files=["data_access/features.py"],
        )
        assert proposal.metadata.author_model == model
        assert proposal.metadata.assigned_branch == branch
        assert proposal.metadata.status == ProposalStatus.DRAFT

        # Load back from disk
        loaded = pm.load_proposal(proposal.id)
        assert loaded.metadata.author_model == model
        assert loaded.metadata.assigned_branch == branch
        assert loaded.id == proposal.id
